app/Http/routes.php
<?php
Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'ProductController@index')->name('product.list');
    Route::resource('products', 'ProductController',  ['except' => ['create', 'store', 'show']]);

    Route::get('/import', 'ImportController@index')->name('import.index');
    Route::post('/import', 'ImportController@process')->name('import.process');
});

app/Models/Product.php
<?php

namespace App\Models;

use App\Presenters\ProductPresenter;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laracasts\Presenter\PresentableTrait;

class Product extends Model
{
    use SoftDeletes;
    use PresentableTrait;

    protected $presenter = ProductPresenter::class;

    protected $fillable = [
        'code',
        'name',
        'free_shipping',
        'description',
        'price',
        'category'
    ];

    protected $dates = [
        'deleted_at'
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ImportController.php
<?php

namespace App\Http\Controllers;

use App\Jobs\ProductImport\ExcelReader;
use App\Jobs\ProductImport\ProcessImport;
use App\Repositories\ProductRepository;
use Validator;
use Illuminate\Http\Request;

class ImportController extends Controller
{
    public function index()
    {
        return view('import/index');
    }

    public function process(Request $request, ProductRepository $repository)
    {
        $validator = Validator::make($request->all(), [
            'file' => 'required|mimes:xlsx|max:5000',
        ]);

        if ($validator->fails()) {
            return redirect('import')
                   ->withErrors($validator);
        }

        $file = $request->file('file');

        $fileName = uniqid() . '.xlsx';
        $file->move(storage_path('app/import'), $fileName);

        $filePath = storage_path('app/import/') . $fileName;
        
        $reader = new ExcelReader($filePath);
        $importJob = new ProcessImport($repository, $reader);
        $this->dispatch($importJob);

        return redirect('import')
               ->with('success', true);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Repositories\ProductRepository;
use App\Http\Requests\UpdateProductRequest;

class ProductController extends Controller
{
    private $repository;

    public function __construct(ProductRepository $repository)
    {
        $this->repository = $repository;
    }

    public function index()
    {
        $products = $this->repository->all();
        return view('product/index', ['products' => $products]);
    }

    public function edit(Product $products)
    {
        return view('product/form', ['product' => $products]);
    }

    public function update(UpdateProductRequest $request, $id)
    {
        $this->repository->update($id, $request->all());
        return redirect('products');
    }

    public function destroy($id)
    {
        $this->repository->delete($id);
        return redirect('products');
    }
}

resources/views/import/index.blade.php
@extends('layout')

@section('content')
    <section class="row">
        <div class="col-xs-offset-3 col-xs-9">
            <h2>Import Products</h2>
            @if ($errors->has('file'))
                <div class="feedback feedback-error">
                    <div class="feedback-title">
                        Fail!
                    </div>
                    {!! $errors->first('file')  !!}
                </div>
            @elseif (Session::get('success') == true)
                <div class="feedback feedback">
                    <div class="feedback-title">
                        Success!
                    </div>
                    Your file will be processed as soon.
                </div>
            @endif

            {!! Form::open(['files' => true, 'route' => 'import.process', 'class' => 'import-form']) !!}
            {!! Form::file('file') !!}
            {!! Form::submit('Send File', ['class' => 'button button-primary']) !!}
            {!! Form::close() !!}
        </div>
    </section>
@endsection

resources/views/layout.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Leroy Merlin</title>
    <link href="{{ asset('favicon.ico') }}" type="image/x-icon" rel="icon"/>
    <link rel="stylesheet" href="{{ asset('css/all.css') }}">
</head>
<body>
<header class="header">
    <div class="container">
        <h1>Leroy Merlin</h1>
        <nav class="nav">
            <a href="{{ route('products.index') }}" class="link">List</a>
            <a href="{{ route('import.index') }}" class="link">Import</a>
        </nav>
    </div>
</header>

<div class="container">
    @yield('content')
</div>
<script src="{{ asset('js/all.js') }}"></script>
</body>
</html>

resources/views/product/form.blade.php
@extends('layout')

@section('content')
    <section class="row">
        <div class="col-xs-12">
            <h2>Product update</h2>
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            {!! Form::model($product, ['method' => 'put', 'route' => ['products.update', $product->id]]) !!}
            {!! Form::hidden('id') !!}

            <div class="row">
                <div class="field col-xs-2">
                    {!! Form::label('code', 'Code') !!}
                    {!! Form::text('code', null, ['disabled'=> true, 'class' => 'input']) !!}
                </div>
            </div>

            <div class="row">
                <div class="field col-xs-6">
                    {!! Form::label('name', 'Name') !!}
                    {!! Form::text('name', null, ['class' => 'input']) !!}
                </div>
            </div>

            <div class="row">
                <div class="field col-xs-2">
                    {!! Form::label('category', 'Category') !!}
                    {!! Form::text('category', null, ['class' => 'input']) !!}
                </div>

                <div class="field col-xs-2">
                    {!! Form::label('price', 'Price $') !!}
                    {!! Form::text('price', null, ['class' => 'input']) !!}
                </div>

                <div class="field col-xs-2">
                    <div class="field input-button checkbox-free-shipping">
                        {!! Form::hidden('free_shipping', 0) !!}
                        {!! Form::checkbox('free_shipping', 1, null, ['id' => 'free_shipping']) !!}
                        {!! Form::label('free_shipping', 'Free Shipping', ['class' => 'label']) !!}
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="field col-xs-6">
                    {!! Form::label('description', 'Description') !!}
                    {!! Form::text('description', null, ['class' => 'input']) !!}
                </div>
            </div>

            <div class="row">
                <div class="field col-xs-6">
                    {!!  Form::submit('Save', ['class' => 'button button-primary']) !!}
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </section>
@endsection

resources/views/product/index.blade.php
@extends('layout')

@section('content')
    <section class="row">
        <h2>Products</h2>
        <div class="col-xs-12">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Code</th>
                        <th>Name</th>
                        <th>Free Shipping</th>
                        <th>Description</th>
                        <th>Price</th>
                        <th>Category</th>
                        <th width="160px">Actions</th>
                    </tr>
                </thead>
                <tbody>
                @foreach ($products as $product)
                    <tr>
                        <td>{{ $product->code }}</td>
                        <td>{{ $product->name }}</td>
                        <td>{{ $product->present()->freeShipping }}</td>
                        <td>{{ $product->description }}</td>
                        <td>{{ $product->present()->pricePresent }}</td>
                        <td>{{ $product->category }}</td>
                        <td>
                            <a href="{{ route('products.edit', ['products' => $product->id]) }}" class="button">edit</a>
                            {!! Form::model($product, ['class' => 'form-delete', 'method' => 'delete', 'route' => ['products.destroy', $product->id]]) !!}
                                <button class=" button button-danger">del</button>
                            {!! Form::close() !!}
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </section>
@endsection